### ISSUE TITLE
Opens old notes with wrong year

### ISSUE THREAD

**Issue by localjo** [frankolson/obsidian-tomorrows-daily-note#11]
When I try to open tomorrow's daily note, it opens notes on tomorrows date from years ago instead.

**Comment by frankolson** [comment]
Hey @localjo, I'm having trouble reproducing this error. Could you provide a screencast showing this happening? It might help might troubleshoot

**Comment by localjo** [comment]
I don't know if this provides any useful information, but here's a screencast of it happening:

https://github.com/frankolson/obsidian-tomorrows-daily-note/assets/516388/a1b3a617-e6c1-4da1-9ee8-eab62f7145ef

**Comment by localjo** [comment]
It looks like this bug originates in `obsidian-daily-notes-interface`: https://github.com/liamcain/obsidian-daily-notes-interface/issues/31

It seems that organizing notes into subdirectories isn't currently supported.

**Comment by localjo** [comment]
Actually, here is the original bug report: https://github.com/liamcain/obsidian-daily-notes-interface/issues/21

Looks like it's been open for some time.

**Comment by frankolson** [comment]
Ahh, okay thanks for updating this @localjo
