### ISSUE TITLE
Icon in sidebar seems to be re-added every time, thus losing positioning in ribbon

### ISSUE THREAD

**Issue by tobischiebel** [frankolson/obsidian-tomorrows-daily-note#14]
Basically the title, the new icon (which I am a huge fan of btw!) keeps appearing at the bottom of the ribbon every time I open Obsidian on Windows.
For now I am using the Commander plugin with the corresponding command that's available and another icon, would love to have this supported directly by your awesome plugin!

**Comment by frankolson** [comment]
Fix released in version [1.2.1](https://github.com/frankolson/obsidian-tomorrows-daily-note/releases/tag/1.2.1)
