### ISSUE TITLE
Feature Request: Enable middle mouse button click to open tomorrow's daily note in new tab

### ISSUE THREAD

**Issue by tobischiebel** [frankolson/obsidian-tomorrows-daily-note#16]
It would be nice for  this to work similarly to the way it is implemented for the native daily note command / button

**Comment by frankolson** [comment]
This is a cool idea! I've started a PR for that here: https://github.com/frankolson/obsidian-tomorrows-daily-note/pull/17

**Comment by frankolson** [comment]
Released in version [1.2.0](https://github.com/frankolson/obsidian-tomorrows-daily-note/releases/tag/1.2.0)

**Comment by tobischiebel** [comment]
Thank you for considering my feature request, now middle mouse button click works, however it does not have the intended behavior. It has the same effect as a normal mouse click and opens it in the current tab instead of a new tab.

**Comment by tobischiebel** [comment]
I apologize, it does work as intended, I was still using the Commander plugin to run the "Open tomorrow's daily note" command, which does not behave the same way for obvious reasons.
