### ISSUE TITLE
Take into account weekend when creating tomorrows dailiy note

### ISSUE THREAD

**Issue by alexeyabel** [frankolson/obsidian-tomorrows-daily-note#7]
It would be nice to be able to skip the weekend when creating "tomorrow's daily note". For example, when creating tomorrows note on Friday, it should create one for Monday, adding the appropriate date to the file name.

The plugin should have a checkbox setting with something similar to "skip Saturday and Sunday when creating tomorrows note".

Thanks for the plug-in. It is very useful :)

**Comment by frankolson** [comment]
Resolved with:
- https://github.com/frankolson/obsidian-tomorrows-daily-note/releases/tag/1.1.0
- https://github.com/frankolson/obsidian-tomorrows-daily-note/pull/12
